### ISSUE TITLE
adding @apiHeader breaks compilation

### ISSUE THREAD

**Issue by sunrize531** [rigwild/apidoc-markdown#10]
## Describe the bug

When I add `@apiHeader` to any of the existing blocks, the compilation breaks with the exception:

```
(node:12928) UnhandledPromiseRejectionWarning: TypeError: ejs:28
    26| <%- sub.type.toUpperCase() %> <%= sub.url %>
    27| ```
 >> 28| <% if (sub.header && sub.header.fields && sub.header.fields.Header.length) { -%>
    29|
    30| ### Headers
    31| | Name    | Type      | Description                          |

Cannot read property 'length' of undefined
    at group.subs.forEach.sub (eval at compile (censored\node_modules\ejs\lib\ejs.js:626:12), <anonymous>:73:72)
    at Array.forEach (<anonymous>)
    at data.forEach.group (eval at compile (censored\node_modules\ejs\lib\ejs.js:626:12), <anonymous>:57:19)
    at Array.forEach (<anonymous>)
    at eval (eval at compile (censored\node_modules\ejs\lib\ejs.js:626:12), <anonymous>:49:13)
    at anonymous (censored\node_modules\ejs\lib\ejs.js:656:17)
    at Object.exports.generate (censored\node_modules\apidoc-markdown\dist\generator.js:69:37)
    at Object.exports.generateMarkdownFileSystem (censored\node_modules\apidoc-markdown\dist\generator.js:127:35)
(node:12928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
(rejection id: 1)
(node:12928) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Breaks even with the header from apidoc documentation:
`@apiHeader (MyHeaderGroup) {String} authorization Authorization value.`

### Usage
Used `apidoc-markdown` command or script.

### `api_project.json`

```
{
  "name": "censored",
  "description": "REST API censored",
  "template": {
    "withCompare": false,
    "withGenerator": false,
    "aloneDisplay": false
  }
}
```

### `api_data.json`
Used `api_data.json` file: can't provide, but nothing really special.

**Expected behavior**
Documentation compiles without exception

**Versions (please complete the following information):**
 - `Node.js` version: `10.15.3`
 - `apiDoc` version: `"~0.20.1`
 - `apidoc-markdown` version: `~5.0.0`

**Comment by rigwild** [comment]
Hi!

I will not be able to help you with the current information.
As you may see, the examples files are compiling successfully.

See :

 - https://github.com/rigwild/apidoc-markdown/blob/master/examples/basic/example.md#Parameters
 - https://github.com/rigwild/apidoc-markdown/blob/master/examples/_apiDocData/src/api_header.js

I also tried with the [official example](https://github.com/apidoc/apidoc/tree/master/example) successfully.

**Comment by sunrize531** [comment]
I have just installed the latest node, and the same doc compiles well. I think this might be something specific to Node 10.

**Comment by rigwild** [comment]
That's weird. This might be related to #8.

I just tried with node `10.15.3` and could not reproduce :confused:

When you updated node, did you recompile with `apidoc` before using `apidoc-markdown` ?

**Comment by sunrize531** [comment]
Yes, I have, I'm compiling docs via package.json script:
```
"doc": "apidoc -i ./api -o ./doc -t ./apidoc-template && apidoc-markdown -p ./doc -o DOCUMENTATION.md && rimraf ./doc"
```

Template just contains an empty html tag in index.html.

**Comment by rigwild** [comment]
Closing for inactivity.
