### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'access' of undefined

### ISSUE THREAD

**Issue by ruturajmaniyar** [rigwild/apidoc-markdown#14]
Already using "ApiDoc" for generation API documentation. Now I want convert it into markdown. 
Then I installed "apidoc-markdown" using below command in my linux system
```bash
sudo npm install apidoc-markdown -g
```
then I tried with below command to generate markdown document

```bash
apidoc -f ".*\\.php$" -i /var/www/html/project-1/src/ -o /var/www/html/api-doc/
```
API doc generated successfully with "api_data.json" and "api_project.json" file

Then I run below command
```bash
apidoc-markdown -p /var/www/html/api-doc/ -o /var/www/html/api-mk-doc/
```
Then I am getting below error:

```bash
(node:28779) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'access' of undefined
    at Object.exports.pathExists (/usr/local/lib/node_modules/apidoc-markdown/dist/utils.js:24:6)
    at Object.exports.generateMarkdownFileSystem (/usr/local/lib/node_modules/apidoc-markdown/dist/generator.js:111:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/apidoc-markdown/bin/index.js:9:26)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
(node:28779) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28779) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Can you please help me out?

I am using Ubuntu : 18.04 LTS system

**Comment by rigwild** [comment]
Hi!
Why don't you first fill the issue template ?

https://raw.githubusercontent.com/rigwild/apidoc-markdown/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by ruturajmaniyar** [comment]
## Describe the bug
Getting below error when I generating API document in markdown format.
> "UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'access' of undefined"

## Reproduce
### Usage
Used `apidoc-markdown` command or script.

```bash
apidoc-markdown -p /var/www/html/api-doc/ -o /var/www/html/api-mk-doc/_mkdoc.md
```

```ts
> I didn't create .ts file because I am following default step that you mentions in readme.md
```

### `api_project.json`
Used `api_project.json` file.

```json
{
  "name": "Project-1-API",
  "version": "3.2.0",
  "description": "",
  "title": "apiDoc - Project - 1",
  "url": "https://{HOST}:{PORT}/api/v{API_VERSION}/customers",
  "header": {
    "title": "Introduction",
    "content": "<p>We provides open source mobile application api that can be integrated with Android and IOS application development.</p>\n"
  },
  "footer": {
    "title": "Support",
    "content": "<p>Copyright © 2019–2020</p>\n"
  },
  "order": [
    "Announcement-API",
    "Announcement-List"
  ],
  "template": {
    "withCompare": true,
    "withGenerator": false
  },
  "sampleRequest": true,
  "sampleUrl": "http://test.api.local:7002/api/v3.2/customers",
  "defaultVersion": "3.0.0",
  "apidoc": "0.3.0",
  "generator": {
    "name": "apidoc",
    "time": "2020-05-29T11:46:37.839Z",
    "url": "http://apidocjs.com",
    "version": "0.22.1"
  }
}
```

### `api_data.json`
Used `api_data.json` file.

```json
[
  {
    "type": "get",
    "url": "/get-announcement",
    "title": "Announcement List",
    "name": "Announcement_List",
    "group": "Announcement-API",
    "description": "<p>Show announcement API List</p>",
    "version": "3.2.0",
    "success": {
      "fields": {
        "200 Success": [
          {
            "group": "200 Success",
            "type": "Number",
            "optional": false,
            "field": "code",
            "description": "<p>Response Code.</p>"
          },
          {
            "group": "200 Success",
            "type": "String",
            "optional": false,
            "field": "message",
            "description": "<p>Response Message.</p>"
          },
          {
            "group": "200 Success",
            "type": "Object[]",
            "optional": false,
            "field": "data",
            "description": "<p>Response Information.</p>"
          },
          {
            "group": "200 Success",
            "type": "Number",
            "optional": false,
            "field": "data.announcement-id",
            "description": "<p>Announcement ID.</p>"
          },
          {
            "group": "200 Success",
            "type": "String",
            "optional": false,
            "field": "data.announcement-title",
            "description": "<p>Announcement Title.</p>"
          },
          {
            "group": "200 Success",
            "type": "String",
            "optional": false,
            "field": "data.announcement-published-on",
            "description": "<p>Announcement Published On.</p>"
          },
          {
            "group": "200 Success",
            "type": "String",
            "optional": false,
            "field": "data.announcement-short-desc",
            "description": "<p>Announcement Short Description.</p>"
          },
          {
            "group": "200 Success",
            "type": "String",
            "optional": false,
            "field": "data.announcement-is-read",
            "description": "<p>Announcement is read flag.</p>"
          }
        ]
      },
      "examples": [
        {
          "title": "Success-Response:",
          "content": "HTTP/1.1 200 OK\nContent-Type: application/json\n{\n     \"code\": 200,\n     \"message\": \"Data fetched successfully\",\n     \"data\": [\n            {\n                 \"announcement-id\": 6,\n                 \"announcement-title\": \"The MAin Progrma!!!!!!!!\",\n                 \"announcement-published-on\": \"3 weeks ago\",\n                 \"announcement-short-desc\": \"This is demo announcement\",\n                 \"announcement-is-read\": \"1\"\n             },\n             {\n                 \"announcement-id\": 5,\n                 \"announcement-title\": \"New Loyalty Program\",\n                 \"announcement-published-on\": \"1 month ago\",\n                 \"announcement-short-desc\": \"test test tewst \",\n                 \"announcement-is-read\": \"0\"\n             }\n           ]\n}",
          "type": "json"
        }
      ]
    },
    "filename": "/var/www/html/api-doc/app/Http/Controllers/v3/v32/AnnouncementController.php",
    "groupTitle": "Announcement-API",
    "sampleRequest": [
      {
        "url": "http://test.api.local:7002/api/v3.2/customers/get-announcement"
      }
    ],
    "header": {
      "fields": {
        "Header": [
          {
            "group": "Header",
            "type": "String",
            "optional": false,
            "field": "Content-Type",
            "defaultValue": "application/json",
            "description": ""
          },
          {
            "group": "Header",
            "type": "String",
            "optional": false,
            "field": "X-auth-token",
            "description": "<p>Authorization Token</p>"
          },
          {
            "group": "Header",
            "type": "String",
            "optional": false,
            "field": "X-device-id",
            "description": "<p>Unique id of Mobile Device</p>"
          },
          {
            "group": "Header",
            "type": "String",
            "optional": false,
            "field": "X-device-name",
            "description": "<p>Mobile Device Model Name</p>"
          },
          {
            "group": "Header",
            "type": "String",
            "optional": false,
            "field": "X-platform",
            "defaultValue": "android",
            "description": "<p>Mobile device OS</p>"
          },
          {
            "group": "Header",
            "type": "String",
            "optional": false,
            "field": "X-platform-version",
            "description": "<p>Current mobile device OS version</p>"
          },
          {
            "group": "Header",
            "type": "String",
            "optional": false,
            "field": "X-device-mac-address",
            "description": "<p>Current mobile MAC Address</p>"
          },
          {
            "group": "Header",
            "type": "String",
            "optional": false,
            "field": "X-app-version",
            "description": "<p>Current Application version</p>"
          },
          {
            "group": "Header",
            "type": "String",
            "optional": false,
            "field": "X-localisation",
            "defaultValue": "en",
            "description": "<p>Application Language</p>"
          }
        ]
      },
      "examples": [
        {
          "title": "Header-Example:",
          "content": "Content-Type:application/json\nX-auth-token:ahDvCGy3ks4Gy2onJSfpVrL2eVFOOj\nX-tenant-member-id:8633958176\nX-device-id:863276df24fa2dfa\nX-device-name:mi a3\nX-platform:android\nX-platform-version:9.0\nX-device-mac-address:8c:3a:e3ff:fe1a:304d\nX-app-version:1.0\nX-localisation:en",
          "type": "Header"
        }
      ]
    },
    "error": {
      "fields": {
        "Error 4xx": [
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "400",
            "description": "<p><b>Bad Request</b>. Indicates that the request by the client was not processed, as the server could not understand what the client is asking for.</p>"
          },
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "401",
            "description": "<p><b>Unauthorized</b>. Indicates that the client is not allowed to access resources, and should re-request with the required credentials.</p>"
          },
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "403",
            "description": "<p><b>Forbidden</b>. Indicates that the request is valid and the client is authenticated, but the client is not allowed access the page or resource for any reason. E.g sometimes the authorized client is not allowed to access the directory on the server.</p>"
          },
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "404",
            "description": "<p><b>Not Found</b>. Indicates that the requested resource is not available now.</p>"
          },
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "405",
            "description": "<p><b>Method Not Allowed</b>. Indicates that the client tried to use an HTTP method that the resource does not allow. For instance, a read-only resource could support only GET, but not POST, PUT or DELETE</p>"
          },
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "500",
            "description": "<p><b>Internal Server Error</b>. Indicates that the request is valid, but the server is totally confused and the server is asked to serve some unexpected condition.</p>"
          },
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "503",
            "description": "<p><b>Service Unavailable</b>. Indicates that the server is down or unavailable to receive and process the request. Mostly if the server is undergoing maintenance.</p>"
          }
        ]
      }
    }
  }
]
```

**Expected behavior**
Expected to convert api-doc in markdown format.

**Versions (please complete the following information):**
 - `Node.js` version: v8.10.0
 - `TypeScript` version: unknown 
 - `apiDoc` version: 0.22.1
 - `apidoc-markdown` version: 5.1.1

**Additional context**
N/A

**Comment by rigwild** [comment]
Thanks for the details. The lib is using the [`fs.promises`](https://nodejs.org/docs/latest-v14.x/api/fs.html#fs_fs_promises_api) node API, which is available starting from Node.js v10+.

I will add a `engine` field in the `package.json` file to make sure future users gets warned when using an unsupported version.

Thanks
