### ISSUE TITLE
The -e <exclude-folders> option does not work

### ISSUE THREAD

**Issue by nmandyam** [rigwild/apidoc-markdown#23]
## Describe the bug
apiDoc supports an option to exclude sub-directories, -e. But apidoc-markdown drops that, so the underlying apiDoc barks and fails. Running apidoc directly works.

### Usage
Working command:
```apidoc -i . -e node_modules -o abcd.html```

Failing command:
```apidoc-markdown -i . -e node_modules -o abcd.html```
Causes this output:
```
D:\AppData\Roaming\nvm\v16.13.1\node_modules\apidoc-markdown\node_modules\apidoc-light\lib\core\parser.js:301
          throw new ParserError('Empty parser result.',
                ^
ParserError: Empty parser result.
    at Parser._parseBlockElements (D:\AppData\Roaming\nvm\v16.13.1\node_modules\apidoc-markdown\node_modules\apidoc-light\lib\core\parser.js:301:17)
    at Parser.parseSource (D:\AppData\Roaming\nvm\v16.13.1\node_modules\apidoc-markdown\node_modules\apidoc-light\lib\core\parser.js:174:15)
    at Parser.parseFile (D:\AppData\Roaming\nvm\v16.13.1\node_modules\apidoc-markdown\node_modules\apidoc-light\lib\core\parser.js:138:15)
    at Parser.parseFiles (D:\AppData\Roaming\nvm\v16.13.1\node_modules\apidoc-markdown\node_modules\apidoc-light\lib\core\parser.js:113:29)
    at D:\AppData\Roaming\nvm\v16.13.1\node_modules\apidoc-markdown\node_modules\apidoc-light\lib\core\index.js:174:20
    at Array.forEach (<anonymous>)
    at Object.parse (D:\AppData\Roaming\nvm\v16.13.1\node_modules\apidoc-markdown\node_modules\apidoc-light\lib\core\index.js:169:19)
    at createDoc (D:\AppData\Roaming\nvm\v16.13.1\node_modules\apidoc-markdown\node_modules\apidoc-light\lib\index.js:79:22)
    at createDocOrThrow (D:\AppData\Roaming\nvm\v16.13.1\node_modules\apidoc-markdown\dist\utils.js:76:46)
    at Object.generateMarkdownFileSystem (D:\AppData\Roaming\nvm\v16.13.1\node_modules\apidoc-markdown\dist\generator.js:118:79) {
  file: '.\\functions\\node_modules\\aws-sdk\\dist\\aws-sdk-core-react-native.js',
  block: 35,
  element: 'api',
  source: '@api private\n' +
    '@!macro [new] nobrowser\n' +
    '  @note This feature is not supported in the browser environment of the SDK.',
  extra: [
    {
      File: '.\\functions\\node_modules\\aws-sdk\\dist\\aws-sdk-core-react-native.js'
    },
    { Block: 35 },
    { Element: '@api' },
    {
      Source: '@api private\n' +
        '@!macro [new] nobrowser\n' +
        '  @note This feature is not supported in the browser environment of the SDK.'
    }
  ]
}
```

### `api_project.json`
Not used `api_project.json` file.

### `api_data.json`
Used `api_data.json` file.

```json
{
  "name": "My APIs",
  "version": "0.1.0",
  "description": "APIs for my product",
  "title": "My APIs",
  "url": "https://example.com/my_apis"
}
```

**Expected behavior**
That the sub-directories named in -e be ignored for the parsing.

**Versions (please complete the following information):**
 - `Node.js` version: `16.3.1`
 - `apiDoc` version: `0.50.3`
 - `apidoc-markdown` version: `7.0.2`

**Additional context**
Only js files in code.

**Comment by rigwild** [comment]
Thanks for the report! I forgot to add back all apiDoc CLI options when migrating to [apidoc-light](https://github.com/rigwild/apidoc-light).

Default ignored files: `['apidoc.config.js', 'node_modules']` so you won't even need to include it for your use case.

Fixed in https://github.com/rigwild/apidoc-markdown/releases/tag/v7.0.4

**Comment by nmandyam** [comment]
Thank you for the update. I'm not sure what I am doing wrong, though: using the apidoc command gives me a folder with nicely-formatted HTML and a sidebar, while using apidoc-markdown gives me a single, much-smaller file that is badly formatted. The markdown is correctly rendered, though.

**Comment by rigwild** [comment]
This lib is only used to generate markdown files. There are some minor spacing issues in some section that I could not fix but most of it respects the markdown spec, and is entirely valid markdown.
