### ISSUE TITLE
require() of ES Module not supported

### ISSUE THREAD

**Issue by JoseGoncalves** [rigwild/apidoc-markdown#28]
## Describe the bug

After upgrading from 7.2.5 to 7.3.0 I'm unable to generate my API docs because the command aborts with error.
The error that I get is this:
```
/home/jmpg/INOV-Git/PRR-ECP/WRP-SRV/node_modules/apidoc-markdown/bin/index.js:12
require('update-notifier')({ pkg: require('../package.json') }).notify()
^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/jmpg/INOV-Git/PRR-ECP/WRP-SRV/node_modules/update-notifier/index.js from /home/jmpg/INOV-Git/PRR-ECP/WRP-SRV/node_modules/apidoc-markdown/bin/index.js not supported.
Instead change the require of /home/jmpg/INOV-Git/PRR-ECP/WRP-SRV/node_modules/update-notifier/index.js in /home/jmpg/INOV-Git/PRR-ECP/WRP-SRV/node_modules/apidoc-markdown/bin/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/jmpg/INOV-Git/PRR-ECP/WRP-SRV/node_modules/apidoc-markdown/bin/index.js:12:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.13.0
```

### Usage

Used `apidoc-markdown` command or script.

```sh
apidoc-markdown -i src -o api.md
```

**Expected behavior**
apidoc-markdown executes without errors.

**Versions (please complete the following information):**

- `Node.js` version: `18.13.0`
- `apidoc-markdown` version: `7.3.0`

**Comment by rigwild** [comment]
Oups! Looks like I upgraded a dependency I shouldn't! Will fix that tomorrow

**Comment by JoseGoncalves** [comment]
I think you can fix this by replacing this line in `bin/index.js`

```js
require('update-notifier')({ pkg: require('../package.json') }).notify()
```

with this usage pattern:

- https://www.npmjs.com/package/update-notifier#simple

**Comment by vicfelipe** [comment]
> ## Describe the bug
> After upgrading from 7.2.5 to 7.3.0 I'm unable to generate my API docs because the command aborts with error. The error that I get is this:
> 
> ```
> /home/jmpg/INOV-Git/PRR-ECP/WRP-SRV/node_modules/apidoc-markdown/bin/index.js:12
> require('update-notifier')({ pkg: require('../package.json') }).notify()
> ^
> 
> Error [ERR_REQUIRE_ESM]: require() of ES Module /home/jmpg/INOV-Git/PRR-ECP/WRP-SRV/node_modules/update-notifier/index.js from /home/jmpg/INOV-Git/PRR-ECP/WRP-SRV/node_modules/apidoc-markdown/bin/index.js not supported.
> Instead change the require of /home/jmpg/INOV-Git/PRR-ECP/WRP-SRV/node_modules/update-notifier/index.js in /home/jmpg/INOV-Git/PRR-ECP/WRP-SRV/node_modules/apidoc-markdown/bin/index.js to a dynamic import() which is available in all CommonJS modules.
>     at Object.<anonymous> (/home/jmpg/INOV-Git/PRR-ECP/WRP-SRV/node_modules/apidoc-markdown/bin/index.js:12:1) {
>   code: 'ERR_REQUIRE_ESM'
> }
> 
> Node.js v18.13.0
> ```
> 
> ## Reproduce
> ### Usage
> Used `apidoc-markdown` command or script.
> 
> ```shell
> apidoc-markdown -i src -o api.md
> ```
> 
> **Expected behavior** apidoc-markdown executes without errors.
> 
> **Versions (please complete the following information):**
> 
> * `Node.js` version: `18.13.0`
> * `apidoc-markdown` version: `7.3.0`

Same problem here.

**Comment by rigwild** [comment]
Fixed in https://github.com/rigwild/apidoc-markdown/commit/7f467908ee0450924b60a106e57fd78f73aadc6a

**Comment by rigwild** [comment]
Not willing to migrate to ESM now because apidoc is not ESM, I don't want to deal with the GitHub issues that will come because of people not able/understanding how to upgrade 😅

**Comment by JoseGoncalves** [comment]
If you need to stick with CommonJS, what about upgrading the `update-notifier` package to the latest (ESM) and importing it in the `apidoc-markdown` script as follows?

```patch
diff --git a/bin/index.js b/bin/index.js
index 8029bc8..4f50e1d 100644
--- a/bin/index.js
+++ b/bin/index.js
@@ -9,4 +9,9 @@ const argv = require('../dist/cli').default
 require('../dist/index').generateMarkdownFileSystem(argv)
 
 // Check for update
-require('update-notifier')({ pkg: require('../package.json') }).notify()
+async function checkUpdate() {
+  const { default: updateNotifier } = await import('update-notifier')
+  updateNotifier({ pkg: require('../package.json') }).notify()
+}
+
+checkUpdate()
```
