### ISSUE TITLE
Cannot read property 'Header' of undefined

### ISSUE THREAD

**Issue by owen-carter** [rigwild/apidoc-markdown#8]
```
[owen@localhost mgt]$  apidoc-markdown -p public/ -o doc.md
(node:24808) ExperimentalWarning: The fs.promises API is experimental
(node:24808) UnhandledPromiseRejectionWarning: TypeError: ejs:29
    27| <%- sub.type.toUpperCase() %> <%= sub.url %>
    28| ```
 >> 29| <% if (sub.header && sub.header.fields.Header.length) { -%>
    30| ### Headers
    31| | Name    | Type      | Description                          |
    32| |---------|-----------|--------------------------------------|

Cannot read property 'Header' of undefined
    at group.subs.forEach.sub (eval at compile (/home/owen/.nvm/versions/node/v10.16.3/lib/node_modules/@rigwild/apidoc-markdown/node_modules/ejs/lib/ejs.js:652:12), <anonymous>:73:44)
    at Array.forEach (<anonymous>)
    at data.forEach.group (eval at compile (/home/owen/.nvm/versions/node/v10.16.3/lib/node_modules/@rigwild/apidoc-markdown/node_modules/ejs/lib/ejs.js:652:12), <anonymous>:57:19)
    at Array.forEach (<anonymous>)
    at eval (eval at compile (/home/owen/.nvm/versions/node/v10.16.3/lib/node_modules/@rigwild/apidoc-markdown/node_modules/ejs/lib/ejs.js:652:12), <anonymous>:49:13)
    at anonymous (/home/owen/.nvm/versions/node/v10.16.3/lib/node_modules/@rigwild/apidoc-markdown/node_modules/ejs/lib/ejs.js:682:17)
    at Object.singleCompiler (/home/owen/.nvm/versions/node/v10.16.3/lib/node_modules/@rigwild/apidoc-markdown/dist/generator.js:100:57)
    at Object.exports.generateMarkdown (/home/owen/.nvm/versions/node/v10.16.3/lib/node_modules/@rigwild/apidoc-markdown/dist/generator.js:114:31)
(node:24808) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24808) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

this exists in all version

**Comment by rigwild** [comment]
Hey @owen-carter !
Could you please show me a repo to reproduce the error so I can dig into it?

All the provided examples in this repo are compiling successfully.

**Comment by owen-carter** [comment]
sorry for that my repo is private and that contains some private data.
but i  have resolved that by provide the template.md file which was modified with me,

before:
`<% if (sub.header && sub.header.fields.Header.length) { -%>`


now:
`<% if (sub.header && sub.header.fields) { -%>`

factlly,i do not resolve the problem in all. just avoid it.

maybe i could send a mail to transfer the api-data.json?

**Comment by rigwild** [comment]
Yes please. My email is on my profile.

**Comment by rigwild** [comment]
@owen-carter I haven't received any email. Should I close this issue ?

**Comment by rigwild** [comment]
Fixed it.
